Repository JoseAugustoJasfarias/soulpet-front, pull requests merged in 2023-05, with the labels that each got.

#32 Modal de deletar produto
  src/pages/Produtos/Produtos.jsx
Labels: documentation, enhancement

#33 Task 04 LucasDamasceno
  src/App.js
  src/pages/NovoCliente/NovoCliente.jsx
  src/pages/NovoPet/NovoPet.jsx
  src/pages/Pets/Pets.jsx
Labels: documentation, enhancement

#34 Task#5 Lucas Damasceno
  src/App.js
  src/pages/EditarPets/EditarPets.jsx
Labels: documentation, enhancement

#35 Página adicionar novo produto
  package-lock.json
  package.json
  src/App.js
  src/pages/NovoProduto/NovoProduto.jsx
  src/pages/Produtos/Produtos.jsx
Labels: documentation, enhancement

#37 Tasks 11 e 12 feitas
  src/App.js
  src/components/Header/Header.jsx
  src/pages/Clientes/Clientes.jsx
  src/pages/Servicos/Servicos.jsx
Labels: documentation, enhancement

#38 Integrar a listagem de Pedidos
  src/App.js
  src/components/Header/Header.jsx
  src/pages/NovoPedido/NovoPedido.jsx
  src/pages/Pedidos/Pedidos.jsx
Labels: documentation, enhancement

#39 Página Dashboard
  src/App.js
  src/components/Header/Header.jsx
  src/pages/DashBoard/DashBoard.jsx
Labels: documentation, enhancement

#40 FE-13
  src/App.js
  src/pages/NovoAgendamento/NovoAgendamento.jsx
Labels: documentation, enhancement

#41 Tasks FE 9 e 10 LucasDamasceno
  src/App.js
  src/pages/EditarServicos/EditarServicos.jsx
  src/pages/NovoServico/NovoServico.jsx
  src/pages/Pets/Pets.jsx
  src/pages/Servicos/Servicos.jsx
Labels: documentation, enhancement

#42 FE-15
  src/App.js
  src/components/Header/Header.jsx
  src/pages/Agendamentos/Agendamentos.jsx
Labels: documentation, enhancement

#43 Task SP7 - LucasDamasceno
  README.md
Labels: documentation, enhancement

#46 correção página de agendamentos
  src/pages/Agendamentos/Agendamentos.jsx
  src/pages/NovoAgendamento/NovoAgendamento.jsx
Labels: bug, enhancement

#48 Criação pagina editar produto e correção em dashboard e produtos
  src/App.js
  src/pages/DashBoard/DashBoard.jsx
  src/pages/EditarProduto/EditarProduto.jsx
  src/pages/Produtos/Produtos.jsx
Labels: documentation, enhancement

#50 Adicionando FiveIcon e nome da pagina novos
  public/index.html
  public/manifest.json
  public/soul-pet-logo.png
Labels: enhancement

#51 Lista IBGE
  src/App.js
  src/IBGEapi/IBGE.js
  src/pages/Agendamentos/Agendamentos.jsx
  src/pages/EditaCliente/EditaCliente.jsx
  src/pages/EditaPedido/EditaPedido.jsx
  src/pages/NovoCliente/NovoCliente.jsx
  src/pages/NovoPedido/NovoPedido.jsx
  src/pages/Pedidos/Pedidos.jsx
Labels: documentation, enhancement

#52 Fixando problemas
  src/pages/Agendamentos/Agendamentos.jsx
Labels: bug, enhancement

#53 Base logica para o codigo de detalhamento de um cliente e Atualização de Agendamentos , Foi melhor que consegui fazer com o tempo proposto.
  src/App.js
  src/pages/Clientes/Clientes.jsx
  src/pages/DetalhesCliente/DetalhesCliente.jsx
  src/pages/EditarAgendamento/EditarAgendamento.jsx
Labels: documentation, enhancement
